// <auto-generated />
using System;
using ContadSp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContadSp.Migrations
{
    [DbContext(typeof(ContadSpContext))]
    [Migration("20240311201423_cambiomodarticulos")]
    partial class cambiomodarticulos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ContadSp.Modelos.Modelo_ABM_Categoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("categoria")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Modelo_ABM_Categoria");
                });

            modelBuilder.Entity("ContadSp.Modelos.Modelo_Articulos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CantidadLetra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CantidadNum")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("fecha_ultimo_monto")
                        .HasColumnType("date");

                    b.Property<string>("foto")
                        .HasColumnType("longtext");

                    b.Property<int>("id_categoria")
                        .HasColumnType("int");

                    b.Property<double>("monto_aprox")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.HasIndex("id_categoria");

                    b.ToTable("Modelo_Articulos");
                });

            modelBuilder.Entity("ContadSp.Modelos.Modelo_Detalle_Pedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<string>("cantidad_letra")
                        .HasColumnType("longtext");

                    b.Property<int>("id_articulo")
                        .HasColumnType("int");

                    b.Property<int>("id_pedido")
                        .HasColumnType("int");

                    b.Property<int>("id_unidad")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("id_articulo");

                    b.HasIndex("id_pedido");

                    b.HasIndex("id_unidad");

                    b.ToTable("Modelo_Detalle_Pedido");
                });

            modelBuilder.Entity("ContadSp.Modelos.Modelo_Pedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("destino")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("fecha_pedido")
                        .HasColumnType("date");

                    b.Property<string>("usuario_solicita")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Modelo_Pedidos");
                });

            modelBuilder.Entity("ContadSp.Modelos.Modelo_Unidad_Medida", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("unidad")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Modelo_Unidad_Medida");
                });

            modelBuilder.Entity("ContadSp.Modelos.Modelo_Articulos", b =>
                {
                    b.HasOne("ContadSp.Modelos.Modelo_ABM_Categoria", "Categoria")
                        .WithMany("Articulos")
                        .HasForeignKey("id_categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ContadSp.Modelos.Modelo_Detalle_Pedido", b =>
                {
                    b.HasOne("ContadSp.Modelos.Modelo_Articulos", "Articulos")
                        .WithMany("Detalle_Pedido")
                        .HasForeignKey("id_articulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContadSp.Modelos.Modelo_Pedido", "Pedido")
                        .WithMany("Detalle_Pedido")
                        .HasForeignKey("id_pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContadSp.Modelos.Modelo_Unidad_Medida", "Unidad_Medida")
                        .WithMany("Detalle_Pedido")
                        .HasForeignKey("id_unidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulos");

                    b.Navigation("Pedido");

                    b.Navigation("Unidad_Medida");
                });

            modelBuilder.Entity("ContadSp.Modelos.Modelo_ABM_Categoria", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("ContadSp.Modelos.Modelo_Articulos", b =>
                {
                    b.Navigation("Detalle_Pedido");
                });

            modelBuilder.Entity("ContadSp.Modelos.Modelo_Pedido", b =>
                {
                    b.Navigation("Detalle_Pedido");
                });

            modelBuilder.Entity("ContadSp.Modelos.Modelo_Unidad_Medida", b =>
                {
                    b.Navigation("Detalle_Pedido");
                });
#pragma warning restore 612, 618
        }
    }
}
