// <auto-generated />
using System;
using ContadSp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContadSp.Migrations
{
    [DbContext(typeof(ContadSpContext))]
    partial class ContadSpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ContadSp.Modelos.Modelo_ABM_Categoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("categoria")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Modelo_ABM_Categoria");
                });

            modelBuilder.Entity("ContadSp.Modelos.Modelo_Articulos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Modelo_Pedidoid")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("fecha_ultimo_monto")
                        .HasColumnType("date");

                    b.Property<int>("id_categoria")
                        .HasColumnType("int");

                    b.Property<double>("monto_aprox")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.HasIndex("Modelo_Pedidoid");

                    b.HasIndex("id_categoria");

                    b.ToTable("Modelo_Articulos");
                });

            modelBuilder.Entity("ContadSp.Modelos.Modelo_Pedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("destino")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("fecha_pedido")
                        .HasColumnType("date");

                    b.Property<string>("usuario_solicita")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Modelo_Pedidos");
                });

            modelBuilder.Entity("ContadSp.Modelos.Modelo_Articulos", b =>
                {
                    b.HasOne("ContadSp.Modelos.Modelo_Pedido", null)
                        .WithMany("Articulos")
                        .HasForeignKey("Modelo_Pedidoid");

                    b.HasOne("ContadSp.Modelos.Modelo_ABM_Categoria", "Categoria")
                        .WithMany("Articulos")
                        .HasForeignKey("id_categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ContadSp.Modelos.Modelo_ABM_Categoria", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("ContadSp.Modelos.Modelo_Pedido", b =>
                {
                    b.Navigation("Articulos");
                });
#pragma warning restore 612, 618
        }
    }
}
